[package]
name = "download_atv_screensavers"
version = "0.1.0"
authors = ["Alex Chan <alex@alexwlchan.net>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0.64"
serde_derive = "1.0.64"
serde_json = "1.0.19"
